### ISSUE TITLE
Getting a quad's color 

### ISSUE THREAD

**Issue by Bauxitedev** [bonsairobo/block-mesh-rs#1]
I'm writing a little Minecraft importer for Godot and I'm using this library to convert a voxel grid into a mesh. Everything seems to work fine but I have one little issue. It seems I can't figure out how to determine which color a quad should be. My code is the following (with some details removed):
```rust
//after running greedy_mesh()...

let num_indices = quads_buffer.quads.num_quads() * 6;
let num_vertices = quads_buffer.quads.num_quads() * 4;
let mut indices = Vec::with_capacity(num_indices);
let mut positions = Vec::with_capacity(num_vertices);
let mut normals = Vec::with_capacity(num_vertices);
let mut uvcoords = Vec::with_capacity(num_vertices);
let mut colors = Vec::with_capacity(num_vertices);

for (quad_group, face) in quads_buffer.quads.groups.into_iter().zip(RIGHT_HANDED_Y_UP_CONFIG.faces) {
	for quad in &quad_group {
		indices.extend_from_slice(&face.quad_mesh_indices(positions.len() as u32));
		positions.extend_from_slice(&face.quad_mesh_positions(&quad, 1.0));
		normals.extend_from_slice(&face.quad_mesh_normals());
		uvcoords.extend_from_slice(&face.tex_coords(RIGHT_HANDED_Y_UP_CONFIG.u_flip_face, true, &quad)); 
	}
}

```

So I was wondering... how do you get the "material index" of a quad, which determines which color it should be? (e.g. grass should have green faces, water should have blue faces, etc)

I tried something like this, using `quad.minimum` to get the minimum voxel a quad belongs to...
```rust
		let [x, y, z] = quad.minimum; 
		let palette_index = &blocks[(x, y, z)];
		let color = palette[palette_index];

		colors.extend_from_slice(&[color; 4]);
```

But that seems to be incorrect, as you can see: (the entire river should be blue, but only parts of it are)
![image](https://user-images.githubusercontent.com/31383123/146166843-31b5c043-0341-4dca-b752-79ecbb50c177.png)

Is my code incorrect?

**Comment by bonsairobo** [comment]
Hmm using `quad.minimum` is supposed to work. How is `Index` implemented for `blocks`?

**Comment by bonsairobo** [comment]
Sidenote: I should make the render example a little more interesting by adding color.

**Comment by Bauxitedev** [comment]
Okay, it turns out swapping X and Z fixes the issue:
```rust
let palette_index = &blocks[(z, y, x)];
```

That seems kinda weird... maybe it has to do with the order of blocks in the array?

I'm using [ndarray](https://docs.rs/ndarray/latest/ndarray/struct.ArrayBase.html) for the storage of voxel data, so the order is row major.

**Comment by bonsairobo** [comment]
Interesting. That means you will need to make sure that the `Shape` you pass in to `greedy_quads` matches the layout of the ndarray thing. Then you can flip your coordinates back.

**Comment by bonsairobo** [comment]
Perhaps `Shape` is not the perfect name, because it is in fact a linearization layout function with an assumed ordering. Read more [here](https://github.com/bonsairobo/ndshape-rs).

**Comment by bonsairobo** [comment]
For performance reasons, `greedy_quads` needs to know the real layout of the slice.

**Comment by bonsairobo** [comment]
Seems like the issue is resolved.
