### ISSUE TITLE
[HELP] Voxel colours or textures.

### ISSUE THREAD

**Issue by Totobird-Creations** [bonsairobo/block-mesh-rs#11]
How can I apply a colour or texture to each type of voxel?

**Comment by bonsairobo** [comment]
Please see `examples-crate/uv_mapping`

**Comment by Totobird-Creations** [comment]
I attempted to run it but I didn't know what it does because this error kept coming up:
```
bevy_asset::asset_server: encountered an error while loading an asset: Error reading image file uv_checker.png: failed to load an image: Format error decoding Png: invalid signature, this is an error in `bevy_render`.
```
It opened just a grey window.

**Comment by bonsairobo** [comment]
Ah sorry. You will need to use git LFS to fetch that image file.

**Comment by Totobird-Creations** [comment]
I have gotten something like the uv mapping example working, but I'm still not sure how to set the uvs based on the individual voxels. What do you recommend?

**Comment by bonsairobo** [comment]
There is a method for extracting UVs from a single quad.

https://docs.rs/block-mesh/0.1.0/block_mesh/struct.OrientedBlockFace.html#method.tex_coords

**Comment by Cyliann** [comment]
Ok, I'm trying to understand that, but I just can't. 
Eg. I want a top of a voxel on (0, 0, 0) to have a texture 'grass.png'. How do I do that?
