### ISSUE TITLE
Voxel Transparency Issue

### ISSUE THREAD

**Issue by JAD3N** [bonsairobo/block-mesh-rs#15]
Hi, I'm using `VoxelVisibility::Translucent` for voxels that have a transparent colour. However, none of the faces of the transparent voxel are returned after greedy meshing even though there are exposed sides.

Is it supposed to only ensure that occluded faces of non-transparent voxels are visible and ignores the faces of the transparent voxel?

**Comment by bonsairobo** [comment]
> Is it supposed to only ensure that occluded faces of non-transparent voxels are visible and ignores the faces of the transparent voxel?

Occluded faces should never be visible, where my definition of occluded means that the face is shared by two non-empty voxels.

See here: https://github.com/bonsairobo/block-mesh-rs/blob/a088508ed7ea4b69b62ea935cf94d141613127a3/src/greedy.rs#L226

> none of the faces of the transparent voxel are returned after greedy meshing even though there are exposed sides.

Maybe we should have an example with translucent voxels just to make sure this actually works. I can try it out real quick with the render example.

**Comment by bonsairobo** [comment]
I just ran the render example with this change:

```
diff --git a/examples-crate/render/main.rs b/examples-crate/render/main.rs
index e5e3e9b..ae100c8 100644
--- a/examples-crate/render/main.rs
+++ b/examples-crate/render/main.rs
@@ -205,7 +205,7 @@ impl Voxel for BoolVoxel {
         if *self == EMPTY {
             VoxelVisibility::Empty
         } else {
-            VoxelVisibility::Opaque
+            VoxelVisibility::Translucent
         }
     }
 }
```

and the voxels are still rendered. I think @JAD3N you will need to provide some code to understand your issue.

**Comment by JAD3N** [comment]
@bonsairobo I've quickly put this together: https://gist.github.com/JAD3N/4999f6f4714f6f958155d15dd83c6fd9

I believe it should output more than 12 faces, but I'm probably making a mistake somewhere but not sure where.

**Comment by bonsairobo** [comment]
I think you're right. I'm not sure why there are 4 missing quads. But it looks like each group has 2 quads, so I'm guessing it's the 4 translucent quads that are missing.

**Comment by bonsairobo** [comment]
Oh actually this is the issue:

```rust
    pub fn is_transparent(&self) -> bool {
        self.color.a != 255
    }

    pub fn is_empty(&self) -> bool {
        self.color.a == 0
    }
    
    ...
    
impl block_mesh::Voxel for Material {
    fn get_visibility(&self) -> block_mesh::VoxelVisibility {
        if self.is_transparent() {
            block_mesh::VoxelVisibility::Translucent
        } else if self.is_empty() {
            block_mesh::VoxelVisibility::Empty
        } else {
            block_mesh::VoxelVisibility::Opaque
        }
    }
}
```

@JAD3N I think your `AIR` voxels end up as `Translucent`. So the non-occluded faces that are shared by `AIR` are getting culled because of this [`TODO`](https://github.com/bonsairobo/block-mesh-rs/blob/a088508ed7ea4b69b62ea935cf94d141613127a3/src/greedy.rs#L243-L244).

**Comment by JAD3N** [comment]
Ah I completely missed that. Thank you for your help with this!

**Comment by bonsairobo** [comment]
No problem! It's kind of a rough edge, since it's not totally obvious that two adjacent, transparent, non-"empty" voxels could have this behavior.

**Comment by JAD3N** [comment]
> @JAD3N I think your `AIR` voxels end up as `Translucent`. So the non-occluded faces that are shared by `AIR` are getting culled because of this [`TODO`](https://github.com/bonsairobo/block-mesh-rs/blob/a088508ed7ea4b69b62ea935cf94d141613127a3/src/greedy.rs#L243-L244).

I see so voxels that are translucent can be skipped if occluded by other translucent voxels  even if they have different merge values? 

Hence why the air which mistakenly is translucent occluded the voxel I was missing but kept the opaque voxels.

**Comment by bonsairobo** [comment]
Yea, if a voxel isn't `VoxelVisibility::Empty`, then it is necessarily an occluder. A `VoxelVisibility::Translucent` occluder can only occlude other `VoxelVisibility::Translucent` voxels though.

That may or may not be the best policy/algorithm, but it's what exists right now.
