### ISSUE TITLE
Update crates package

### ISSUE THREAD

**Issue by Yairama** [bonsairobo/block-mesh-rs#20]
Hello!

The package dowloaded from https://crates.io/crates/block-mesh through cargo.toml have a different MergeVoxel trait (doesnt have MergeValueFacingNeighbour type and function).

Is this trait is critic?

thats all!

**Comment by bonsairobo** [comment]
@Yairama Yea this is expected. There were some recent changes to the trait on the `main` branch. I'll publish a new release after I get #19 merged. I just haven't made time for this in a while since I don't actually use this crate for anything personally.
