### ISSUE TITLE
[Feature request] Editing a mesh

### ISSUE THREAD

**Issue by Inspirateur** [bonsairobo/block-mesh-rs#24]
Hi, thanks a lot for your crate. Do you think you could add a function to modify the VertexAttributeValues to edit a specific face ?
This would be useful to update the meshes when it changes after its creation.

**Comment by bonsairobo** [comment]
@Inspirateur You should consider just regenerating your mesh when the underlying data changes. This can be done efficiently by chunking your data.

**Comment by Inspirateur** [comment]
> @Inspirateur You should consider just regenerating your mesh when the underlying data changes. This can be done efficiently by chunking your data.

fair. it's what i'm currently doing but i was thinking it could be faster, i guess not significantly  👍
