### ISSUE TITLE
[HELP] Struggling to understand how to apply textures to faces

### ISSUE THREAD

**Issue by Cassumbra** [bonsairobo/block-mesh-rs#26]
I don't understand how this is intended to be done. I think I almost get it? But I feel like I'm just grasping at the air so I don't know if I truly get it.
So
I need to iterate over all the quads, right? And then... I need to figure out what block they correspond to? Can I do that by indexing my chunk with "minimum"??? What does minimum mean? Is that the 3d index for the block that they correspond to? or is that like... one of the corners of the quad? I don't understand.
I need to get the corresponding block for each quad so i can use the block to figure out what texture to use, right? I feel like I could figure things out from there, but. I just. Don't get it.
What is a minimum. Why is it called that? Why is there not a proper example for this? It feels like a common thing users would want to do is map textures to their chunk meshes. There looks like there's an example for UV mapping, but it looks like it just cyclically assigns textures to faces?
Also, I can't even run the UV mapping example even if i do git lfs fetch.

**Comment by Cassumbra** [comment]
actually, give me a moment, just realized i might want to play with giving the mesher something other than bool voxels and maybe looking at doing that will help me out some
of course, there's a good chance that i will remain clueless, but i'll go ahead and look at that first and then come back if i remain a stump without clue

**Comment by Cassumbra** [comment]
no, that actually has nothing to do with my problem and confusion, because the only data the voxel trait stores is if its empty, transluscent, or opaque

**Comment by Cassumbra** [comment]
i feel like the problem might be one of documentation? i dont even know
https://docs.rs/block-mesh/0.2.0/block_mesh/struct.UnorientedUnitQuad.html
does the minimum field refer to the coordinates of the voxel it corresponds to? if so, why doesn't it just say that? why is it called minimum? what is a minimum voxel?

**Comment by bonsairobo** [comment]
Have you looked at this?

https://github.com/bonsairobo/block-mesh-rs/blob/main/examples-crate/uv_mapping/main.rs

**Comment by Cassumbra** [comment]
Going to write something up here for anyone confused about the same thing I was.
My code is a modified version of the simple mesh generation.
https://github.com/jameshiew/block-mesh-rs/blob/fix-examples/examples-crate/render/main.rs

        let num_indices = buffer.num_quads() * 6;
        let num_vertices = buffer.num_quads() * 4;
        let mut indices = Vec::with_capacity(num_indices);
        let mut positions = Vec::with_capacity(num_vertices);
        let mut normals = Vec::with_capacity(num_vertices);
        let mut uvs = Vec::with_capacity(num_vertices);
        for (group, face) in buffer.groups.into_iter().zip(faces.into_iter()) {
            for quad in group.into_iter() {
                indices.extend_from_slice(&face.quad_mesh_indices(positions.len() as u32));
                positions.extend_from_slice(&face.quad_mesh_positions(&quad.into(), 1.0));
                normals.extend_from_slice(&face.quad_mesh_normals());

                let block_id = chunk[UVec3::from(quad.minimum) - UVec3::new(1, 1, 1)];
                let attributes = block_id.get_attributes();
                let normal = face.signed_normal();

                let tex_coord = if normal.x == 1 {attributes.tex_coords.east}
                             else if normal.x == -1 {attributes.tex_coords.west}
                             else if normal.y == 1 {attributes.tex_coords.top}
                             else if normal.y == -1 {attributes.tex_coords.bottom}
                             else if normal.z == 1 {attributes.tex_coords.north}
                             else {attributes.tex_coords.west};

                let quad_uvs = face.tex_coords(RIGHT_HANDED_Y_UP_CONFIG.u_flip_face, true, &UnorientedQuad::from(quad)).map(|uv| {
                    let mut u = uv[0] * 8.0;
                    let mut v = uv[1] * 8.0;
                    if u != 0.0 {u -= 1.0};
                    if v != 0.0 {v -= 1.0};
                    u += tex_coord.x as f32 * 8.0;
                    v += tex_coord.y as f32 * 8.0;
                    [u/256.0, v/256.0]
                });

                uvs.extend_from_slice(&quad_uvs);
            }
        }
        
And later:


    render_mesh.insert_attribute(
            Mesh::ATTRIBUTE_UV_0,
            VertexAttributeValues::Float32x2(uvs),
        );
        
To explain some magic numbers, 8x8 is the size of the textures in my atlas, while 256x256 is the size of the atlas itself.

https://docs.rs/block-mesh/latest/block_mesh/struct.UnorientedUnitQuad.html

Minimum is what you want for finding the coordinates of the voxel for the face so that you can figure out how to texture the face. The documentation is written confusingly, but this _is_ what you're looking for.
