### ISSUE TITLE
Voxel trait easily confused

### ISSUE THREAD

**Issue by dcz-self** [bonsairobo/block-mesh-rs#5]
The Voxel trait contains 2 similar functions: `is_empty` and `is_opaque` with close but opposite meanings. Most of the times I was implementing them, I wanted to copy-paste them, but that would cause one to have the completely wrong meaning. How about turning `is_opaque` to `is_translucent`?

I'm also not quite sure how `is_opaque` influences mesh generation, but if it means "does not prevent inner quads from showing", then "is_empty" is strictly a subset of "is_translucent", and the 3 would have been better served by an enum:

```
enum VoxelVisibility {
   Empty,
   Translucent,
   Opaque,
}
```

How does that sound?

**Comment by bonsairobo** [comment]
Yea I like the proposed `enum VoxelVisibility`. I would accept a PR for that.

**Comment by bonsairobo** [comment]
Done! Thank you for the PR.
